language: python

python:
  - "2.6"
  - "2.7"

jdk:
  - openjdk6
  - openjdk7

script: |
  java -version; ./build-support/bin/ci.sh -d

notifications:
  email:
      - john.sirois@gmail.com
      - lhosken@twitter.com
      - zundel@squareup.com
      - benjyw@gmail.com
      - areitz@twitter.com

