# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='android-example',
  source='HelloWorld.java',
  main='example/src/com/pants/examples/hello/*.java'
)