# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

android_binary(name='android-example',
  sources='HelloWorld.java',
  home=[pants('src/android/example')],
  package='com.pants.examples.hello',
  resources=[
   pants('src/android/example/res')
    ],
)